# Generated by Django 3.2.16 on 2024-03-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('09db4f', 'GREEN'), ('ffff00', 'YELLOW'), ('b813d1', 'PURPLE')], max_length=7, unique=True, verbose_name='Цвет'),
        ),
    ]
