# Generated by Django 3.2.16 on 2024-03-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_tag_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredientrecipe",
            options={
                "verbose_name": "Ингредиент рецепта",
                "verbose_name_plural": "Ингредиенты рецепта",
            },
        ),
    ]
