# Generated by Django 3.2.16 on 2024-03-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ingredientrecipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='нет картинки', help_text='Добавьте изображение рецепта', upload_to='media/', verbose_name='Картинка рецепта'),
        ),
    ]
