# Generated by Django 3.2.16 on 2024-03-25 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['recipe'], 'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['following']},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ['ingredient'], 'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецепта'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ['recipe'], 'verbose_name': 'Рецепт для покупки', 'verbose_name_plural': 'Рецепты для покупки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_not_followed_himself',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique follow',
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Укажите количество ингредиента', validators=[django.core.validators.MinValueValidator(1, 'Минимальное время приготовления'), django.core.validators.MaxValueValidator(32000, 'Максимальное время приготовления')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Укажите время приготовления рецепта в минутах', validators=[django.core.validators.MinValueValidator(1, 'Минимальное время приготовления'), django.core.validators.MaxValueValidator(32000, 'Максимальное время приготовления')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#32CD32', 'GREEN'), ('#FFFF00', 'YELLOW'), ('#800080', 'PURPLE')], max_length=7, unique=True, verbose_name='Цвет'),
        ),
    ]
